name: scalifra
description: Agenda Digital Rede Scalifra

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.44+44

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies: 
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

#
  audioplayers: ^1.0.1
#  audioplayer_web: 0.7.1
  auto_size_text: ^3.0.0
  # Android, IOS, WEB
  bloc_pattern: 3.0.0
  # Android, IOS, WEB
  bubble: 1.2.1
  # Android, IOS, WEB
  cached_network_image: ^3.2.0
  # Android, IOS
  cloud_firestore: ^2.4.0
  # Android, IOS, WEB
  cloud_functions: ^3.3.1
  # Android, IOS, WEB
  csv: 5.0.0
  # Android, IOS, WEB
  cupertino_icons: ^0.1.3
  # Android, IOS, WEB
  file: ^6.1.2
  file_picker: ^4.6.1
  # Android, IOS
  firebase_core: ^1.1.0
  firebase:
  # Web
  firebase_analytics: ^9.1.12
  firebase_auth: ^3.0.1
  # Android, IOS, WEB
  firebase_messaging: ^11.4.4
  # Android, IOS
#  firebase_ml_vision:
#  # Android, IOS
  firebase_storage: ^10.0.1
  # Android, IOS
  #flutter_audio_recorder: ^0.5.5
  # Android, IOS
  flutter_cache_manager: ^3.3.0
  flutter_launcher_icons:
  # Android, IOS
  flutter_linkify:
  # Android, IOS, WEB
  #flutter_plugin_pdf_viewer: ^1.0.7
  # Android, IOS
  flutter_tts:
  # Android, IOS, WEB
  google_fonts: ^3.0.1
  # ANDROID IOS LINUX MACOS WEB WINDOWS
  image_cropper:
  # Android, IOS
  image_picker:
  # Android, IOS
  intl:
  # Android, IOS, WEB
  #masked_text: ^0.0.6
  # Android, IOS, WEB
  modal_bottom_sheet:
  # Android, IOS, WEB
  multi_image_picker:
  # Android, IOS
  #multiple_select:
  # Android, IOS, WEB
  package_info:
  # Android, IOS, WEB
  path_provider: ^2.0.11
  # Android, IOS
  photo_view: 0.13.0
  # Android, IOS, WEB
  rxdart: ^0.27.4
  # Android, IOS, WEB
  simple_rc4:
  # Android, IOS, WEB
  shimmer:
  # Android, IOS, WEB
  table_calendar:
  # Android, IOS, WEB
  toast:
  # Android, IOS, WEB
  #universal_html: ^1.2.1
  url_launcher:
  # Android, IOS, WEB
  via_cep:
  # Android, IOS, WEB
  video_player:
  # Android, IOS, WEB
  webview_flutter: ^3.0.4
  # Android, IOS
  youtube_player_flutter: 8.0.0
  # Android, IOS
  uuid: ^3.0.1
flutter_icons:
         image_path_android: "images/logoredondo.png"
         image_path_ios: "images/logoredondo.png"
         android: true
         ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#dependency_overrides:
#  intl: ^0.17.0-nullsafety.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Sans
      fonts:
        - asset: font/OpenSans-Semibold.ttf
          weight: 600
        - asset: font/OpenSans-Regular.ttf
          weight: 400
        - asset: font/OpenSans-Light.ttf
          weight: 200


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
